# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmEdifPubMilitarP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipoedifmil', models.CharField(blank=True, null=True, max_length=26)),
                ('tipousoedif', models.CharField(blank=True, null=True, max_length=21)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'adm_edif_pub_militar_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AglomeradoRuralDeExtensaoUrbana',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'loc_aglomerado_rural_de_extensao_urbana_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AglomeradoRuralIsolado',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipoaglomrurisol', models.CharField(blank=True, null=True, max_length=35)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'loc_aglomerado_rural_isolado_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AldeiaIndigena',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('codigofunai', models.CharField(blank=True, null=True, max_length=15)),
                ('terraindigena', models.CharField(blank=True, null=True, max_length=100)),
                ('etnia', models.CharField(blank=True, null=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'loc_aldeia_indigena_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaDesenvolvimentoControle',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('classificacao', models.CharField(blank=True, null=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_area_desenvolvimento_controle_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaEdificada',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geocodigo', models.CharField(blank=True, null=True, max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'loc_area_edificada_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BancoAreia',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipobanco', models.CharField(blank=True, null=True, max_length=14)),
                ('situacaoemagua', models.CharField(blank=True, null=True, max_length=17)),
                ('materialpredominante', models.CharField(blank=True, null=True, max_length=27)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_banco_areia_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barragem',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('usoprincipal', models.CharField(blank=True, null=True, max_length=15)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_barragem_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrejoPantano',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('alturamediaindividuos', models.FloatField(null=True, blank=True)),
                ('classificacaoporte', models.CharField(blank=True, null=True, max_length=12)),
                ('tipobrejopantano', models.CharField(blank=True, null=True, max_length=27)),
                ('denso', models.CharField(blank=True, null=True, max_length=12)),
                ('antropizada', models.CharField(blank=True, null=True, max_length=23)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'veg_brejo_pantano_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipocapital', models.CharField(blank=True, null=True, max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'loc_capital_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'loc_cidade_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corredeira',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_corredeira_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurvaBatimetrica',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('profundidade', models.IntegerField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_curva_batimetrica_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurvaNivel',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('cota', models.IntegerField(null=True, blank=True)),
                ('depressao', models.CharField(blank=True, null=True, max_length=3)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('indice', models.CharField(blank=True, null=True, max_length=16)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_curva_nivel_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Duna',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('fixa', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_duna_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eclusa',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('desnivel', models.FloatField(null=True, blank=True)),
                ('largura', models.FloatField(null=True, blank=True)),
                ('extensao', models.FloatField(null=True, blank=True)),
                ('calado', models.FloatField(null=True, blank=True)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_eclusa_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EcoExtMineralP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tiposecaocnae', models.CharField(blank=True, null=True, max_length=50)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('tipoextmin', models.CharField(blank=True, null=True, max_length=20)),
                ('tipoprodutoresiduo', models.CharField(blank=True, null=True, max_length=40)),
                ('tipopocomina', models.CharField(blank=True, null=True, max_length=15)),
                ('procextracao', models.CharField(blank=True, null=True, max_length=12)),
                ('formaextracao', models.CharField(blank=True, null=True, max_length=12)),
                ('atividade', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'eco_ext_mineral_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdifAgropecExtVegetalPesca',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('tipoedifagropec', models.CharField(blank=True, null=True, max_length=50)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'eco_edif_agropec_ext_vegetal_pesca_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdifConstPortuaria',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipoedifport', models.CharField(blank=True, null=True, max_length=23)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_edif_const_portuaria_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdifConstrAeroportuaria',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('tipoedifaero', models.CharField(blank=True, null=True, max_length=23)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_edif_constr_aeroportuaria_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdifIndustrial',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('chamine', models.CharField(blank=True, null=True, max_length=3)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('tipodivisaocnae', models.CharField(blank=True, null=True, max_length=180)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'eco_edif_industrial_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdifMetroFerroviaria',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('multimodal', models.CharField(blank=True, null=True, max_length=12)),
                ('funcaoedifmetroferrov', models.CharField(blank=True, null=True, max_length=44)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_edif_metro_ferroviaria_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdifPubMilitar',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipoedifmil', models.CharField(blank=True, null=True, max_length=26)),
                ('tipousoedif', models.CharField(blank=True, null=True, max_length=21)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'adm_edif_pub_militar_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdifReligiosa',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('religiao', models.CharField(blank=True, null=True, max_length=100)),
                ('tipoedifrelig', models.CharField(blank=True, null=True, max_length=12)),
                ('ensino', models.CharField(blank=True, null=True, max_length=12)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'edu_edif_religiosa_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElementoFisiograficoNatural',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipoelemnat', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_elemento_fisiografico_natural_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('employee_id', models.IntegerField(null=True, blank=True)),
                ('name', models.CharField(blank=True, null=True, max_length=30)),
                ('hire_date', models.DateField(null=True, blank=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstGeradEnergiaEletrica',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('codigoestacao', models.CharField(blank=True, null=True, max_length=30)),
                ('potenciaoutorgada', models.IntegerField(null=True, blank=True)),
                ('potenciafiscalizada', models.IntegerField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('tipoestgerad', models.CharField(blank=True, null=True, max_length=15)),
                ('destenergelet', models.CharField(blank=True, null=True, max_length=56)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'enc_est_gerad_energia_eletrica_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtMineral',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tiposecaocnae', models.CharField(blank=True, null=True, max_length=50)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('tipoextmin', models.CharField(blank=True, null=True, max_length=20)),
                ('tipoprodutoresiduo', models.CharField(blank=True, null=True, max_length=40)),
                ('tipopocomina', models.CharField(blank=True, null=True, max_length=15)),
                ('procextracao', models.CharField(blank=True, null=True, max_length=12)),
                ('formaextracao', models.CharField(blank=True, null=True, max_length=12)),
                ('atividade', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'eco_ext_mineral_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FozMaritima',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_foz_maritima_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fundeadouro',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('destinacaofundeadouro', models.CharField(blank=True, null=True, max_length=43)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_fundeadouro_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HidCorredeiraP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_corredeira_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HidQuedaDaguaP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('altura', models.FloatField(null=True, blank=True)),
                ('tipoqueda', models.CharField(blank=True, null=True, max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_queda_dagua_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HidRecifeP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tiporecife', models.CharField(blank=True, null=True, max_length=16)),
                ('situamare', models.CharField(blank=True, null=True, max_length=35)),
                ('situacaocosta', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_recife_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hidreletrica',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('potenciaoutorgada', models.IntegerField(null=True, blank=True)),
                ('potenciafiscalizada', models.IntegerField(null=True, blank=True)),
                ('codigohidreletrica', models.CharField(blank=True, null=True, max_length=30)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'enc_hidreletrica_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HidRochaEmAguaP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('alturalamina', models.FloatField(null=True, blank=True)),
                ('situacaoemagua', models.CharField(blank=True, null=True, max_length=17)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_rocha_em_agua_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ilha',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipoilha', models.CharField(blank=True, null=True, max_length=8)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_ilha_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimTerraIndigenaP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('perimetrooficial', models.FloatField(null=True, blank=True)),
                ('areaoficialha', models.FloatField(null=True, blank=True)),
                ('grupoetnico', models.CharField(blank=True, null=True, max_length=100)),
                ('datasituacaojuridica', models.CharField(blank=True, null=True, max_length=20)),
                ('situacaojuridica', models.CharField(blank=True, null=True, max_length=23)),
                ('nometi', models.CharField(blank=True, null=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
                ('codigofunai', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_terra_indigena_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mangue',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('alturamediaindividuos', models.FloatField(null=True, blank=True)),
                ('classificacaoporte', models.CharField(blank=True, null=True, max_length=12)),
                ('denso', models.CharField(blank=True, null=True, max_length=12)),
                ('antropizada', models.CharField(blank=True, null=True, max_length=23)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'veg_mangue_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcoDeLimite',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipomarcolim', models.CharField(blank=True, null=True, max_length=13)),
                ('latitude', models.CharField(blank=True, null=True, max_length=20)),
                ('longitude', models.CharField(blank=True, null=True, max_length=20)),
                ('altitudeortometrica', models.FloatField(null=True, blank=True)),
                ('orgresp', models.CharField(blank=True, null=True, max_length=10)),
                ('sistemageodesico', models.CharField(blank=True, null=True, max_length=16)),
                ('outrarefplan', models.CharField(blank=True, null=True, max_length=20)),
                ('outrarefalt', models.CharField(blank=True, null=True, max_length=20)),
                ('referencialaltim', models.CharField(blank=True, null=True, max_length=16)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_marco_de_limite_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MassaDagua',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipomassadagua', models.CharField(blank=True, null=True, max_length=18)),
                ('salinidade', models.CharField(blank=True, null=True, max_length=16)),
                ('regime', models.CharField(blank=True, null=True, max_length=31)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_massa_dagua_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geocodigo', models.CharField(blank=True, null=True, max_length=15)),
                ('anodereferencia', models.IntegerField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_municipio_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderpart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('order_id', models.IntegerField(null=True, blank=True)),
                ('part_id', models.IntegerField(null=True, blank=True)),
                ('quantity', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'orderpart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutrasUnidProtegidas',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('anocriacao', models.IntegerField(null=True)),
                ('sigla', models.CharField(blank=True, null=True, max_length=6)),
                ('areaoficial', models.CharField(blank=True, null=True, max_length=15)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('tipooutunidprot', models.CharField(blank=True, null=True, max_length=30)),
                ('historicomodificacao', models.CharField(blank=True, null=True, max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_outras_unid_protegidas_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutrosLimitesOficiais',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('coincidecomdentrode', models.CharField(blank=True, null=True, max_length=50)),
                ('extensao', models.FloatField(null=True, blank=True)),
                ('obssituacao', models.CharField(blank=True, null=True, max_length=100)),
                ('tipooutlimofic', models.CharField(blank=True, null=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_outros_limites_oficiais_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('sigla', models.CharField(blank=True, null=True, max_length=3)),
                ('codiso3166', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_pais_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('part_id', models.IntegerField(null=True, blank=True)),
                ('name', models.CharField(blank=True, null=True, max_length=30)),
                ('cost', models.DecimalField(null=True, decimal_places=2, max_digits=8, blank=True)),
                ('weight', models.FloatField(null=True, blank=True)),
                ('employee_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'part',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pico',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_pico_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PistaPontoPouso',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('largura', models.FloatField(null=True, blank=True)),
                ('extensao', models.FloatField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('homologacao', models.CharField(blank=True, null=True, max_length=12)),
                ('tipopista', models.CharField(blank=True, null=True, max_length=14)),
                ('usopista', models.CharField(blank=True, null=True, max_length=15)),
                ('revestimento', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_pista_ponto_pouso_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ponte',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('tipoponte', models.CharField(blank=True, null=True, max_length=12)),
                ('modaluso', models.CharField(blank=True, null=True, max_length=15)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('vaolivrehoriz', models.FloatField(null=True, blank=True)),
                ('vaovertical', models.FloatField(null=True, blank=True)),
                ('cargasuportmaxima', models.FloatField(null=True, blank=True)),
                ('nrpistas', models.IntegerField(null=True, blank=True)),
                ('nrfaixas', models.IntegerField(null=True, blank=True)),
                ('extensao', models.FloatField(null=True, blank=True)),
                ('largura', models.FloatField(null=True, blank=True)),
                ('posicaopista', models.CharField(blank=True, null=True, max_length=13)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_ponte_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontoCotadoAltimetrico',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('cota', models.FloatField(null=True, blank=True)),
                ('cotacomprovada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_ponto_cotado_altimetrico_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontoCotadoBatimetrico',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('profundidade', models.FloatField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_ponto_cotado_batimetrico_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontosExibicaoWgs84',
            fields=[
                ('id_gps', models.IntegerField(primary_key=True, serialize=False)),
                ('long_decimal', models.FloatField(null=True, blank=True)),
                ('lat_decimal', models.FloatField(null=True, blank=True)),
                ('sistema_geodesico', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True)),
            ],
            options={
                'db_table': 'pontos_exibicao_wgs84',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostoFiscal',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('tipopostofisc', models.CharField(blank=True, null=True, max_length=22)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'adm_posto_fiscal_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuedaDagua',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('altura', models.FloatField(null=True, blank=True)),
                ('tipoqueda', models.CharField(blank=True, null=True, max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_queda_dagua_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recife',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tiporecife', models.CharField(blank=True, null=True, max_length=16)),
                ('situamare', models.CharField(blank=True, null=True, max_length=35)),
                ('situacaocosta', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_recife_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelElementoFisiograficoNaturalP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipoelemnat', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'rel_elemento_fisiografico_natural_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RochaEmAgua',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('alturalamina', models.FloatField(null=True, blank=True)),
                ('situacaoemagua', models.CharField(blank=True, null=True, max_length=17)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_rocha_em_agua_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('order_id', models.IntegerField(null=True, blank=True)),
                ('customer_id', models.IntegerField(null=True, blank=True)),
                ('employee_id', models.IntegerField(null=True, blank=True)),
                ('order_date', models.DateField(null=True, blank=True)),
                ('ship_date', models.DateField(null=True, blank=True)),
                ('payment', models.DecimalField(null=True, decimal_places=2, max_digits=8, blank=True)),
            ],
            options={
                'db_table': 'salesorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesorder1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('order_id', models.IntegerField(null=True, blank=True)),
                ('customer_oid', models.TextField(null=True, blank=True)),
                ('employee_oid', models.TextField(null=True, blank=True)),
                ('part_oid', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'salesorder1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sinalizacao',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('tiposinal', models.CharField(blank=True, null=True, max_length=21)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_sinalizacao_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SumidouroVertedouro',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('causa', models.CharField(blank=True, null=True, max_length=25)),
                ('tiposumvert', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_sumidouro_vertedouro_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Termeletrica',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('potenciaoutorgada', models.IntegerField(null=True, blank=True)),
                ('potenciafiscalizada', models.IntegerField(null=True, blank=True)),
                ('combrenovavel', models.CharField(blank=True, null=True, max_length=3)),
                ('tipomaqtermica', models.CharField(blank=True, null=True, max_length=33)),
                ('geracao', models.CharField(blank=True, null=True, max_length=20)),
                ('tipocombustivel', models.CharField(blank=True, null=True, max_length=17)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'enc_termeletrica_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerraIndigena',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('perimetrooficial', models.FloatField(null=True, blank=True)),
                ('areaoficialha', models.FloatField(null=True, blank=True)),
                ('grupoetnico', models.CharField(blank=True, null=True, max_length=100)),
                ('datasituacaojuridica', models.CharField(blank=True, null=True, max_length=20)),
                ('situacaojuridica', models.CharField(blank=True, null=True, max_length=23)),
                ('nometi', models.CharField(blank=True, null=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
                ('codigofunai', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_terra_indigena_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerrenoSujeitoInundacao',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('periodicidadeinunda', models.CharField(blank=True, null=True, max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_terreno_sujeito_inundacao_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLogradouro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('cod_setor', models.BigIntegerField(null=True, blank=True)),
                ('cod_situacao_setor', models.CharField(blank=True, null=True, max_length=2)),
                ('cod_tipo_setor', models.CharField(blank=True, null=True, max_length=2)),
                ('cod_especie', models.CharField(blank=True, null=True, max_length=2)),
                ('nom_tipo_seglogr', models.CharField(blank=True, null=True, max_length=20)),
                ('nom_titulo_seglogr', models.CharField(blank=True, null=True, max_length=30)),
                ('nom_seglogr', models.CharField(blank=True, null=True, max_length=60)),
                ('num_endereco', models.IntegerField(null=True, blank=True)),
                ('dsc_modificador', models.CharField(blank=True, null=True, max_length=7)),
                ('nom_comp_elem1', models.CharField(blank=True, null=True, max_length=20)),
                ('val_comp_elem1', models.CharField(blank=True, null=True, max_length=10)),
                ('nom_comp_elem2', models.CharField(blank=True, null=True, max_length=20)),
                ('val_comp_elem2', models.CharField(blank=True, null=True, max_length=10)),
                ('nom_comp_elem3', models.CharField(blank=True, null=True, max_length=20)),
                ('val_comp_elem3', models.CharField(blank=True, null=True, max_length=10)),
                ('nom_comp_elem4', models.CharField(blank=True, null=True, max_length=20)),
                ('val_comp_elem4', models.CharField(blank=True, null=True, max_length=10)),
                ('nom_comp_elem5', models.CharField(blank=True, null=True, max_length=20)),
                ('val_comp_elem5', models.CharField(blank=True, null=True, max_length=10)),
                ('nom_comp_elem6', models.CharField(blank=True, null=True, max_length=20)),
                ('val_comp_elem6', models.CharField(blank=True, null=True, max_length=10)),
                ('dsc_ponto_referencia', models.CharField(blank=True, null=True, max_length=60)),
                ('dsc_localidade', models.CharField(blank=True, null=True, max_length=60)),
                ('cep_face', models.CharField(blank=True, null=True, max_length=8)),
                ('val_latitude_padrao', models.CharField(blank=True, null=True, max_length=15)),
                ('val_longitude_padrao', models.CharField(blank=True, null=True, max_length=15)),
                ('dsc_estabelecimento', models.CharField(blank=True, null=True, max_length=40)),
                ('cod_indicador_estab_endereco', models.CharField(blank=True, null=True, max_length=1)),
                ('cod_indicador_const_endereco', models.CharField(blank=True, null=True, max_length=1)),
                ('cod_indicador_finalidade_const', models.CharField(blank=True, null=True, max_length=1)),
                ('cod_indicador_const_endereco2', models.CharField(blank=True, null=True, max_length=1)),
            ],
            options={
                'db_table': 't_logradouro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TorreEnergia',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('alturaestimada', models.FloatField(null=True, blank=True)),
                ('arranjofases', models.CharField(blank=True, null=True, max_length=50)),
                ('ovgd', models.CharField(blank=True, null=True, max_length=12)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('tipotorre', models.CharField(blank=True, null=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'enc_torre_energia_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TraTravessiaP',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('tipotravessia', models.CharField(blank=True, null=True, max_length=18)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_travessia_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travessia',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('tipotravessia', models.CharField(blank=True, null=True, max_length=18)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_travessia_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrechoDrenagem',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('dentrodepoligono', models.CharField(blank=True, null=True, max_length=3)),
                ('compartilhado', models.CharField(blank=True, null=True, max_length=3)),
                ('eixoprincipal', models.CharField(blank=True, null=True, max_length=3)),
                ('caladomax', models.FloatField(null=True, blank=True)),
                ('larguramedia', models.FloatField(null=True, blank=True)),
                ('velocidademedcorrente', models.FloatField(null=True, blank=True)),
                ('profundidademedia', models.FloatField(null=True, blank=True)),
                ('coincidecomdentrode', models.CharField(blank=True, null=True, max_length=35)),
                ('navegabilidade', models.CharField(blank=True, null=True, max_length=16)),
                ('regime', models.CharField(blank=True, null=True, max_length=31)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_trecho_drenagem_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrechoDuto',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('nrdutos', models.IntegerField(null=True, blank=True)),
                ('tipotrechoduto', models.CharField(blank=True, null=True, max_length=22)),
                ('mattransp', models.CharField(blank=True, null=True, max_length=12)),
                ('setor', models.CharField(blank=True, null=True, max_length=21)),
                ('posicaorelativa', models.CharField(blank=True, null=True, max_length=15)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('situacaoespacial', models.CharField(blank=True, null=True, max_length=11)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_trecho_duto_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrechoFerroviario',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('codtrechoferrov', models.CharField(blank=True, null=True, max_length=25)),
                ('posicaorelativa', models.CharField(blank=True, null=True, max_length=15)),
                ('tipotrechoferrov', models.CharField(blank=True, null=True, max_length=12)),
                ('bitola', models.CharField(blank=True, null=True, max_length=27)),
                ('eletrificada', models.CharField(blank=True, null=True, max_length=12)),
                ('nrlinhas', models.CharField(blank=True, null=True, max_length=12)),
                ('emarruamento', models.CharField(blank=True, null=True, max_length=12)),
                ('jurisdicao', models.TextField(null=True, blank=True)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('concessionaria', models.CharField(blank=True, null=True, max_length=100)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('cargasuportmaxima', models.FloatField(null=True, blank=True)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_trecho_ferroviario_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrechoHidroviario',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('extensaotrecho', models.FloatField(null=True, blank=True)),
                ('caladomaxseca', models.FloatField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('regime', models.CharField(blank=True, null=True, max_length=31)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_trecho_hidroviario_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrechoMassaDagua',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('tipotrechomassa', models.CharField(blank=True, null=True, max_length=13)),
                ('salinidade', models.CharField(blank=True, null=True, max_length=16)),
                ('regime', models.CharField(blank=True, null=True, max_length=31)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'hid_trecho_massa_dagua_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrechoRodoviario',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('codtrechorodov', models.CharField(blank=True, null=True, max_length=25)),
                ('tipotrechorod', models.TextField(null=True, blank=True)),
                ('jurisdicao', models.TextField(null=True, blank=True)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('concessionaria', models.CharField(blank=True, null=True, max_length=100)),
                ('revestimento', models.TextField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('nrpistas', models.IntegerField(null=True, blank=True)),
                ('nrfaixas', models.IntegerField(null=True, blank=True)),
                ('trafego', models.TextField(null=True, blank=True)),
                ('canteirodivisorio', models.CharField(blank=True, null=True, max_length=4)),
                ('capaccarga', models.DecimalField(null=True, decimal_places=6, max_digits=19, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_trecho_rodoviario_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tunel',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('modaluso', models.CharField(blank=True, null=True, max_length=15)),
                ('nrpistas', models.IntegerField(null=True, blank=True)),
                ('nrfaixas', models.IntegerField(null=True, blank=True)),
                ('extensao', models.FloatField(null=True, blank=True)),
                ('altura', models.FloatField(null=True, blank=True)),
                ('largura', models.FloatField(null=True, blank=True)),
                ('posicaopista', models.CharField(blank=True, null=True, max_length=13)),
                ('situacaofisica', models.TextField(null=True, blank=True)),
                ('operacional', models.CharField(blank=True, null=True, max_length=12)),
                ('matconstr', models.CharField(blank=True, null=True, max_length=18)),
                ('tipotunel', models.CharField(blank=True, null=True, max_length=28)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'tra_tunel_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeConservacaoNaoSnuc',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('anocriacao', models.IntegerField(null=True, blank=True)),
                ('sigla', models.CharField(blank=True, null=True, max_length=6)),
                ('areaoficial', models.CharField(blank=True, null=True, max_length=15)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('classificacao', models.CharField(blank=True, null=True, max_length=100)),
                ('atolegal', models.CharField(blank=True, null=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_unidade_conservacao_nao_snuc_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeFederacao',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('sigla', models.CharField(blank=True, null=True, max_length=3)),
                ('geocodigo', models.CharField(blank=True, null=True, max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_unidade_federacao_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeProtecaoIntegral',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('anocriacao', models.IntegerField(null=True, blank=True)),
                ('sigla', models.CharField(blank=True, null=True, max_length=6)),
                ('areaoficial', models.CharField(blank=True, null=True, max_length=15)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('atolegal', models.CharField(blank=True, null=True, max_length=100)),
                ('tipounidprotinteg', models.CharField(blank=True, null=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_unidade_protecao_integral_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeUsoSustentavel',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('anocriacao', models.IntegerField(null=True, blank=True)),
                ('sigla', models.CharField(blank=True, null=True, max_length=6)),
                ('areaoficial', models.CharField(blank=True, null=True, max_length=15)),
                ('administracao', models.TextField(null=True, blank=True)),
                ('atolegal', models.CharField(blank=True, null=True, max_length=100)),
                ('tipounidusosust', models.CharField(blank=True, null=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'lim_unidade_uso_sustentavel_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VDescricao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('description', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'v_descricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('animal_id', models.IntegerField(null=True, blank=True)),
                ('name', models.CharField(blank=True, null=True, max_length=20)),
            ],
            options={
                'db_table': 'vegetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VegRestinga',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('alturamediaindividuos', models.FloatField(null=True, blank=True)),
                ('classificacaoporte', models.CharField(blank=True, null=True, max_length=12)),
                ('denso', models.CharField(blank=True, null=True, max_length=12)),
                ('antropizada', models.CharField(blank=True, null=True, max_length=23)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'veg_veg_restinga_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vila',
            fields=[
                ('id_objeto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, null=True, max_length=100)),
                ('nomeabrev', models.CharField(blank=True, null=True, max_length=50)),
                ('geometriaaproximada', models.CharField(blank=True, null=True, max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=0, null=True, blank=True)),
            ],
            options={
                'db_table': 'loc_vila_p',
                'managed': False,
            },
        ),
    ]
